### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by OgelGames** [OgelGames/fakelib#1]
- ~~Add `fakelib.use()`, `fakelib.punch()`, `fakelib.dig()` and `fakelib.place()`, replicating their respective actions.~~
- ~~Add `fakelib.leftclick()` and `fakelib.rightclick()`,  replicating their respective behavior, using a raycast to obtain a pointed thing and determine the action to execute.~~ Too dependent on the specific case to be implemented as generic functions.
- [x] Add API documentation, in the same format as `vizlib`'s (https://github.com/OgelGames/vizlib/blob/master/API.md)
- [x] Release on ContentDB, and mention in https://github.com/minetest/minetest/issues/11477.
- [x] Make PRs for mods that implement their own fake player.
     - https://github.com/mt-mods/pipeworks/pull/126
     - https://github.com/BuckarooBanzay/digibuilder/pull/22
     - https://github.com/minetest-mods/digtron/pull/101
     - https://github.com/minetest-mods/torch_bomb/pull/10
     - https://github.com/joe7575/techage/pull/170
- [x] Make PRs for mods to use fake inventory.
     - https://github.com/mt-mods/unified_inventory_plus/pull/27
     - https://github.com/mt-mods/pipeworks/issues/67
